### PR TITLE
Update UHD to 4.6.0

### PR DESCRIPTION
**Pull request by srcejon**
For [#1974](https://github.com/f4exb/sdrangel/issues/1974)

### CODE REVIEW

**Comment by Ali6114** [comment]
SDRangel crashes when we change the sample rate of the usrp device in runtime. Also, it cannot handle the higher sample rate greater than 20MHz.  Is there some problem with the handling of higher sample rate data like up to 120MHz? I am using X310 using a 1G Ethernet connection.

**Comment by srcejon** [comment]
> SDRangel crashes when we change the sample rate of the usrp device in runtime.

Can you use a debugger to create a stack trace?

> Also, it cannot handle the higher sample rate greater than 20MHz. Is there some problem with the handling of higher sample rate data like up to 120MHz? I am using X310 using a 1G Ethernet connection.

What do you mean by it cannot handle? You can't set higher sample rates in the GUI or your computer can't process that amount of data? I've used higher rates on the B210.

You can't use 120MSa/s over 1G anyway. 120e6*24 > 1e9!

**Comment by Ali6114** [comment]
Currently, I have set the below settings. Fortunately, SDRangel doesn't crash but the spectrum & Waterfall updating/processing becomes slow.
image
Why does the error occur on the above sample rate? is it due to the PC processing issue?
O

**Comment by Ali6114** [comment]
Also, I have increased the sample rate and now the SDRangel stops processing the data and both error LEDs become red as shown in the below figure.
image
is there a way we can specify the number of samples (like 1024) we need in the whole bandwidth/Samplerate instead of acquiring all the data?

**Comment by srcejon** [comment]
You can't run at 50MHz over 1G Ethernet (assuming 12-bit samples) - 50e6*24 > 1G

>is there a way we can specify the number of samples (like 1024) we need in the whole bandwidth/Samplerate instead of acquiring all the data?

I don't know what you mean by this. If you only require a limited bandwidth, then set that as the sample rate and adjust the centre frequency accordingly

**Comment by Ali6114** [comment]
> I don't know what you mean by this. If you only require a limited bandwidth, then set that as the sample rate and adjust the centre frequency accordingly

In LabVIEW, there is an option to set the number of samples. Check the below image.
image

Can we use the X310 through MIXI Cable / PCIe port.

**Pull request merged**
